### PR TITLE
Add shoptalk and smashing video

### PR DESCRIPTION
**Pull request by mirisuzanne**

### CODE REVIEW

**Comment by mirisuzanne** [comment]
I'm not sure when/if to feature various things. I did go back and feature learning with Jason, because that one seemed popular.

**Review by SondraE — APPROVED** [review]
LGTM
As for when to feature, I think it would be good to feature things we want people to notice and also things that are popular so people coming to the site can find them more easily.

By that metic we could also feature: Winging It htmx, SQLAlchemy article, and Unintuitive Objects article.
We could un-feature [When to Choose a Responsive Web App](https://www.oddbird.net/2023/07/11/when-to-choose-a-responsive-web-app/).

**Comment by mirisuzanne** [comment]
> By that metic we could also feature: Winging It htmx, SQLAlchemy article, and Unintuitive Objects article.

@SondraE The old or new SQLAlchemy article? I assume the new one?

**Review by jgerigmeyer — APPROVED** [review]
Looks good. If we want, I'll also note that we have the option to "pin" certain posts to the homepage, otherwise it'll just cycle through the most recent.

**Pull request merged**
