### PR TITLE
[Wingingit4] Winging It 4 Post

### PR DESCRIPTION
**Pull request by stacyk**
## Description
Add Winging It 4 post
Add Polyfill separator between Source and Demo [Trello](https://trello.com/c/psIffPxj/238-add-separator-to-match-between-demo-and-source-on-https-wwwoddbirdnet-polyfill-cascade-layers-polyfill) 

## Steps to test/reproduce
- [ ] Visit Winging it tag page to see episode 4 in list https://deploy-preview-453--oddleventy.netlify.app/wingingit/
- [ ] Visit Episode 4 Post Single https://deploy-preview-453--oddleventy.netlify.app/2023/11/21/winging-it-04/
- [ ] Visit homepage to see it in the Featured Posts section https://deploy-preview-453--oddleventy.netlify.app
- [ ] Visit  https://deploy-preview-453--oddleventy.netlify.app/polyfill/#cascade-layers-polyfill to see separator

## TODO
- [x]  Update video link when it is uploaded
- [ ]  Update publish date if not today

## Show me
home
single-with-old-video
list
polyfill

### CODE REVIEW

**Comment by stacyk** [comment]
[Add separator to match between demo and source on https://www.oddbird.net/polyfill/#cascade-layers-polyfill](https://trello.com/c/psIffPxj/238-add-separator-to-match-between-demo-and-source-on-https-wwwoddbirdnet-polyfill-cascade-layers-polyfill)

**Comment by stacyk** [comment]
[Episode 04 - OOUX Object Maps](https://trello.com/c/dSNsCqjK/31-episode-04-ooux-object-maps)

**Review by SondraE — APPROVED** [review]
Looking really good!
A few ideas for tweaking the text.

What we cover:

- How an object map works
- Demonstration of an object map
- How object maps support database schema development
- Using object maps to communicate more effectively across stakeholders
- How object maps support design systems
- Gauging complexity and aiding prioritization with object maps

Could we use the fullscreen link to the XD demos instead?

- https://xd.adobe.com/view/0941ed26-762a-48b7-88e2-0e89f5b1307f-5c12/?fullscreen
- https://xd.adobe.com/view/930b3686-1ec4-4043-a6e1-6b6caedb9cd3-c658/?fullscreen

Could we add the link to the other OOUX Winging It video and the OOUX article, and recommend that they consume one of these first to understand what objects are?
https://deploy-preview-453--oddleventy.netlify.app/2023/11/09/unintuitive-objects/
https://deploy-preview-453--oddleventy.netlify.app/2023/10/24/winging-it-03/

**Comment by stacyk** [comment]
@SondraE I made the changes you suggested here: https://deploy-preview-453--oddleventy.netlify.app/2023/11/21/winging-it-04/ 

Now all we have left for the Site portion is to update the video URL and set the publish date (if not today).

**Review by jerivas — APPROVED** [review]

**Review by dvdherron — APPROVED** [review]
This all looks good to me. 

A small thing that shouldn't hold this up: Under Featured Posts on the home page the OOUX image is shorter than the rest when there are four columns. I'm guessing it's something to do with the dimensions of the image? 

image

**Comment by stacyk** [comment]
This will fix the image height @dvdherron https://trello.com/c/WdcjO5hj/234-consider-giving-the-post-grid-article-grid-hero-area-a-fixed-height-so-images-look-consistent-on-post-grid-pages

**Pull request merged**
