### PR TITLE
Clarify the dates added to bird subtitles

### PR DESCRIPTION
**Pull request by mirisuzanne**
## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

- go to any bird detail page

## Show me
_Provide screenshots/animated gifs/videos if necessary._

Screen Shot 2022-09-29 at 12 43 59 PM

### CODE REVIEW

**Comment by mirisuzanne** [comment]
[Clarify author detail pages, subheading "since 20xx"](https://trello.com/c/PV65zxkL/176-clarify-author-detail-pages-subheading-since-20xx)

**Review by jgerigmeyer — APPROVED** [review]

**Comment by jgerigmeyer** [comment]
@jerivas Is there an easy way to fix the shadow repo stuff on these PRs where it was broken when they were created? If not, I can compare manually. (Also: #243)

**Review by SondraE — APPROVED** [review]
LGTM. 
There are a few other little things I see like Sana's title "Software Developer" is the only title that has the second word capitalized, and Aura's name could be updated, if they would like. But those aren't actually in this story's scope.

**Comment by mirisuzanne** [comment]
> LGTM. There are a few other little things I see like Sana's title "Software Developer" is the only title that has the second word capitalized, and Aura's name could be updated, if they would like. But those aren't actually in this story's scope.

@SondraE do you want to make new cards for those? Or just open a PR for the first one, and ping Aura about the second?

**Comment by jerivas** [comment]
> @jerivas Is there an easy way to fix the shadow repo stuff on these PRs?

I manually created the branches in the shadow repo and re ran the workflows. I think the links are working now

**Comment by jgerigmeyer** [comment]
> Sana's title "Software Developer" is the only title that has the second word capitalized

Fixed in https://github.com/oddbird/oddleventy/pull/244/commits/3d44324a2b78acc1810cafbba64d658e6abd23e0

> Aura's name could be updated, if they would like

There's already a story for that: https://trello.com/c/Xy8wDiuf/163-update-patricia-aura

**Pull request merged**
