### PR TITLE
Upgrade deps.

### PR DESCRIPTION
**Pull request by jgerigmeyer**

### CODE REVIEW

**Review by jerivas — APPROVED** [review]

**Comment by jgerigmeyer** [comment]
The upgrade to 11ty image caching contained here reduces build time (locally) from ~3min to ~1min.

**Comment by jgerigmeyer** [comment]
Locally:

- Before (`@11ty/eleventy-img v0.10.0`): 3m 1s
- After (`@11ty/eleventy-img v1.0.0-beta.2`, no cache): 3m 35s
- After (`@11ty/eleventy-img v1.0.0-beta.2`, cached): 1m 14s

Netlify:

- Before (`@11ty/eleventy-img v0.10.0`): 6m 41s
- After (`@11ty/eleventy-img v1.0.0-beta.2`, no cache): 8m 55s

So it seems this is actually slightly slower if caching is not enabled. It is locally by default, but I think it'd be worth trying out [caching on Netlify](https://github.com/zeroby0/netlify-plugin-11ty).

**Review by mirisuzanne — APPROVED** [review]
from what I can, this nightmare of a diff looks fine! 😅

We only load the first 3000 changed files

**Comment by jgerigmeyer** [comment]
[I want image assets cached on Netlify.](https://trello.com/c/HuEi4Y8A/148-i-want-image-assets-cached-on-netlify)

**Review by jgerigmeyer — COMMENTED** [review]
@jerivas Updated in https://github.com/oddbird/oddleventy/pull/176/files/783aefc3107eacabc59dad5d3140905832c4b8bc..b82a5eba55e7dc031a2fe78afa917183d4f515b3

Netlify:

- Before (`@11ty/eleventy-img v0.10.0`): 6m 41s
- After (`@11ty/eleventy-img v1.0.0-beta.2`, no cache): 8m 55s
- After (`@11ty/eleventy-img v1.0.0-beta.2`, cached): **2m 23s**

**Comment by jerivas** [comment]
> Netlify:
> 
> * Before (`@11ty/eleventy-img v0.10.0`): 6m 41s
> * After (`@11ty/eleventy-img v1.0.0-beta.2`, no cache): 8m 55s
> * After (`@11ty/eleventy-img v1.0.0-beta.2`, cached): **2m 23s**

@jgerigmeyer It looks like the current GitHub Actions performance for the `shadow-push` job is similar to the uncached case on Netlify (around 7m to build the project and push). I can look into caching on GitHub as well if you think it's worth it.

**Comment by jerivas** [comment]
Yeah, you can cache any folder with https://github.com/actions/cache. Most package manager actions use it behind the scenes to cache dependencies but I think we can adapt it. I'll give it a try on a separate PR.

**Review by jerivas — APPROVED** [review]

**Pull request merged**
