### PR TITLE
Adding Sana as a new bird

### PR DESCRIPTION
**Pull request by sanajaved7**
## Description
Adding Sana to Oddbird site
Adding illustration of Sana to Oddbird site 

## Steps to test/reproduce
Visit /about

## Show me
_Provide screenshots/animated gifs/videos if necessary._

# Trello card
https://trello.com/c/s29ifcRn

### CODE REVIEW

**Comment by sanajaved7** [comment]
[Adding Sana to OddSite](https://trello.com/c/s29ifcRn/160-adding-sana-to-oddsite)

**Review by mirisuzanne — APPROVED** [review]
looks good!

**Review by jgerigmeyer — APPROVED** [review]
🚀

**Comment by jgerigmeyer** [comment]
@sanajaved7 This looks great -- I think you can go ahead and merge at your leisure, then also move the Trello card over into the "Done" list 🎉

**Pull request merged**
